# Generated by Django 4.1.5 on 2023-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discord_id', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('roles', models.TextField(blank=True, null=True)),
                ('joined', models.TextField(blank=True, null=True)),
                ('access', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
